title: thedata.zone
author: Paul Vermette
description: turning data into business value

# social links
twitter_username: paulvermette
linkedin_username: paulvermette

show_excerpts: true # set to true to show excerpts on the homepage
excerpt_separator: <!--more-->

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
